// fixture.js — the demo tournament's data, generated by
// tools/demo_fixture.mjs. Regenerate with `node tools/demo_fixture.mjs`;
// never edit by hand. Served entirely in-browser by app/js/demo.js.
export default {
 "name": "Demo Tournament",
 "currentRound": 3,
 "rooms": [
  "Room A",
  "Room B"
 ],
 "readerRoom": 0,
 "settings": {
  "gameFormat": "macf-powers"
 },
 "packets": {
  "1": {
   "name": "Demo Packet 1",
   "tossups": [
    {
     "question": "The narrator of this novel rents a cottage next to a mansion whose guests gossip that their host once killed a man. A green light at the end of a dock (*) transfixes this novel's title character, who longs for Daisy Buchanan. For 10 points, name this Jazz Age novel by F. Scott Fitzgerald.",
     "answer": "The <b><u>Great Gatsby</u></b>",
     "category": "Literature",
     "subcategory": "American Literature"
    },
    {
     "question": "This ruler crushed a combined Austrian and Russian army at Austerlitz. After a disastrous invasion of (*) Russia, this ruler abdicated and was exiled to Elba, returning for a Hundred Days that ended at Waterloo. For 10 points, name this French emperor.",
     "answer": "<b><u>Napoleon</u></b> Bonaparte [accept <b><u>Napoleon</u></b> I]",
     "category": "History",
     "subcategory": "European History"
    },
    {
     "question": "The second law of thermodynamics states that this quantity never decreases in an isolated system. Ludwig Boltzmann related it to the (*) number of microstates through a logarithm. For 10 points, name this quantity symbolized S, a measure of disorder.",
     "answer": "<b><u>entropy</u></b>",
     "category": "Science",
     "subcategory": "Physics"
    },
    {
     "question": "This novel's title character is locked in the red-room as a child at Gateshead and later teaches at Lowood School. She flees (*) Thornfield Hall after learning her employer keeps his wife Bertha Mason in the attic. For 10 points, name this Charlotte Bronte novel about a governess who loves Mr. Rochester.",
     "answer": "<b><u>Jane Eyre</u></b>",
     "category": "Literature",
     "subcategory": "British Literature"
    },
    {
     "question": "Robert Livingston and James Monroe negotiated this transaction, prompted in part by the Haitian Revolution. It roughly (*) doubled the size of the United States for fifteen million dollars. For 10 points, name this 1803 deal in which Thomas Jefferson bought territory from France.",
     "answer": "<b><u>Louisiana Purchase</u></b>",
     "category": "History",
     "subcategory": "American History"
    },
    {
     "question": "The light-dependent reactions of this process split water molecules to generate ATP and NADPH. Its dark reactions fix (*) carbon dioxide in the Calvin cycle. For 10 points, name this process by which chloroplasts in green plants turn sunlight into sugar.",
     "answer": "<b><u>photosynthesis</u></b>",
     "category": "Science",
     "subcategory": "Biology"
    },
    {
     "question": "A cypress tree rises like a dark flame on the left side of this painting, whose village church spire the artist added from (*) memory while at an asylum in Saint-Remy. For 10 points, name this swirling nighttime scene by Vincent van Gogh.",
     "answer": "The <b><u>Starry Night</u></b>",
     "category": "Fine Arts",
     "subcategory": "Visual Fine Arts"
    },
    {
     "question": "During this observance, a pre-dawn meal called suhoor precedes daily abstention from food and drink. Its end is celebrated at (*) Eid al-Fitr, and the Quran was first revealed during it on the Night of Power. For 10 points, name this Islamic holy month of fasting.",
     "answer": "<b><u>Ramadan</u></b>",
     "category": "Religion",
     "subcategory": ""
    },
    {
     "question": "This river passes through the Iron Gates gorge on the border of Serbia and Romania. Rising in Germany's (*) Black Forest, it flows through more national capitals than any other river, including Vienna and Budapest. For 10 points, name this second-longest river of Europe.",
     "answer": "<b><u>Danube</u></b> River",
     "category": "Geography",
     "subcategory": ""
    },
    {
     "question": "A recurring item in this video game series is the Master Sword, often drawn from a pedestal deep in a forest. Its protagonist collects pieces of the (*) Triforce and rescues a princess of Hyrule from Ganon. For 10 points, name this Nintendo series starring Link.",
     "answer": "The Legend of <b><u>Zelda</u></b>",
     "category": "Trash",
     "subcategory": ""
    }
   ],
   "bonuses": [
    {
     "leadin": "The Buendia family founds the town of Macondo in this author's most famous novel. For 10 points each:",
     "parts": [
      "Name this Colombian author of One Hundred Years of Solitude.",
      "Garcia Marquez wrote in this literary style, which weaves fantastical events into otherwise ordinary settings.",
      "In this Garcia Marquez novel, Florentino Ariza waits more than fifty years to reunite with Fermina Daza."
     ],
     "answers": [
      "Gabriel <b><u>Garcia Marquez</u></b>",
      "<b><u>magical realism</u></b>",
      "<b><u>Love in the Time of Cholera</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Literature",
     "subcategory": "World Literature"
    },
    {
     "leadin": "This city's traditional founding date is 753 BC. For 10 points each:",
     "parts": [
      "Name this city, ruled by seven legendary kings before it became a republic.",
      "This first Roman emperor defeated Antony and Cleopatra at Actium.",
      "Augustus's rise ended decades of civil war that began when this general crossed the Rubicon."
     ],
     "answers": [
      "<b><u>Rome</u></b>",
      "<b><u>Augustus</u></b> [accept <b><u>Octavian</u></b>]",
      "Julius <b><u>Caesar</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "History",
     "subcategory": "Ancient History"
    },
    {
     "leadin": "These elements make up group 18 of the periodic table. For 10 points each:",
     "parts": [
      "Name this family of largely unreactive elements.",
      "This lightest noble gas is the second-most abundant element in the universe.",
      "This noble gas glows reddish-orange in signs and lends its name to them."
     ],
     "answers": [
      "<b><u>noble gas</u></b>es [accept <b><u>inert gas</u></b>es]",
      "<b><u>helium</u></b>",
      "<b><u>neon</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Science",
     "subcategory": "Chemistry"
    },
    {
     "leadin": "Three witches greet this character as Thane of Cawdor and king hereafter. For 10 points each:",
     "parts": [
      "Name this Scottish general who murders King Duncan in his namesake Shakespeare tragedy.",
      "Macbeth is finally slain by this nobleman, who was from his mother's womb untimely ripped.",
      "This wife of Macbeth sleepwalks while trying to wash imagined blood from her hands."
     ],
     "answers": [
      "<b><u>Macbeth</u></b>",
      "<b><u>Macduff</u></b>",
      "<b><u>Lady Macbeth</u></b> [prompt on Macbeth]"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Literature",
     "subcategory": "British Literature"
    },
    {
     "leadin": "A Parisian crowd stormed the Bastille on July 14, 1789. For 10 points each:",
     "parts": [
      "The Bastille's fall began this revolution, which overthrew the Bourbon monarchy.",
      "This radical Jacobin leader dominated the Committee of Public Safety during the Reign of Terror.",
      "This king was executed by guillotine in January 1793."
     ],
     "answers": [
      "<b><u>French Revolution</u></b>",
      "Maximilien <b><u>Robespierre</u></b>",
      "<b><u>Louis XVI</u></b> [prompt on Louis]"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "History",
     "subcategory": "European History"
    },
    {
     "leadin": "This planet's Great Red Spot is a storm that has raged for centuries. For 10 points each:",
     "parts": [
      "Name this largest planet in the solar system.",
      "This Galilean moon of Jupiter is the most volcanically active body in the solar system.",
      "Io and Jupiter's other large moons were discovered in 1610 by this Italian astronomer."
     ],
     "answers": [
      "<b><u>Jupiter</u></b>",
      "<b><u>Io</u></b>",
      "<b><u>Galileo</u></b> Galilei"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Science",
     "subcategory": "Other Science"
    },
    {
     "leadin": "A critic coined this movement's name from a painting of a sunrise over Le Havre. For 10 points each:",
     "parts": [
      "Name this nineteenth-century French movement that captured fleeting effects of light.",
      "This Impressionist painted Impression, Sunrise as well as a series of water lilies at Giverny.",
      "This Impressionist is known for paintings of ballet dancers such as The Dance Class."
     ],
     "answers": [
      "<b><u>Impressionism</u></b>",
      "Claude <b><u>Monet</u></b>",
      "Edgar <b><u>Degas</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Fine Arts",
     "subcategory": "Visual Fine Arts"
    },
    {
     "leadin": "This religion's Trimurti consists of Brahma, Vishnu, and Shiva. For 10 points each:",
     "parts": [
      "Name this major religion of India.",
      "This Hindu concept names the cycle of death and rebirth.",
      "This dialogue between Krishna and Arjuna forms part of the Mahabharata."
     ],
     "answers": [
      "<b><u>Hinduism</u></b>",
      "<b><u>samsara</u></b> [prompt on reincarnation]",
      "<b><u>Bhagavad Gita</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Religion",
     "subcategory": ""
    },
    {
     "leadin": "This continent's highest peak is Kilimanjaro. For 10 points each:",
     "parts": [
      "Name this continent.",
      "This longest river of Africa flows north through Egypt to the Mediterranean.",
      "This Ethiopian capital hosts the headquarters of the African Union."
     ],
     "answers": [
      "<b><u>Africa</u></b>",
      "<b><u>Nile</u></b> River",
      "<b><u>Addis Ababa</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Geography",
     "subcategory": ""
    },
    {
     "leadin": "This studio's films open with a hopping desk lamp. For 10 points each:",
     "parts": [
      "Name this animation studio behind Toy Story.",
      "In this Pixar film, the rat Remy cooks in a Paris restaurant.",
      "This Pixar film about personified emotions takes place largely inside the mind of a girl named Riley."
     ],
     "answers": [
      "<b><u>Pixar</u></b>",
      "<b><u>Ratatouille</u></b>",
      "<b><u>Inside Out</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Trash",
     "subcategory": ""
    }
   ]
  },
  "2": {
   "name": "Demo Packet 2",
   "tossups": [
    {
     "question": "This novel's protagonist beats his wife during the Week of Peace and accidentally kills a clansman, forcing seven years of exile. Its title comes from a (*) Yeats poem, and it ends after Okonkwo hangs himself. For 10 points, name this novel of Igbo life by Chinua Achebe.",
     "answer": "<b><u>Things Fall Apart</u></b>",
     "category": "Literature",
     "subcategory": "World Literature"
    },
    {
     "question": "According to the Secret History written after his death, this ruler was born clutching a blood clot. Originally named (*) Temujin, he united the steppe tribes in 1206. For 10 points, name this founder of the Mongol Empire.",
     "answer": "<b><u>Genghis Khan</u></b> [accept <b><u>Temujin</u></b> before mention]",
     "category": "History",
     "subcategory": "World History"
    },
    {
     "question": "August Kekule claimed that a dream of a snake biting its own tail revealed this molecule's structure. Its six (*) delocalized pi electrons make it the classic aromatic compound. For 10 points, name this hydrocarbon with formula C6H6, a six-membered carbon ring.",
     "answer": "<b><u>benzene</u></b>",
     "category": "Science",
     "subcategory": "Chemistry"
    },
    {
     "question": "In this novel, the drunkard Marmeladov is trampled by a carriage, and his daughter Sonya follows the protagonist to Siberia. Its main character kills the (*) pawnbroker Alyona Ivanovna with an axe. For 10 points, name this Dostoevsky novel about the student Raskolnikov.",
     "answer": "<b><u>Crime and Punishment</u></b>",
     "category": "Literature",
     "subcategory": "European Literature"
    },
    {
     "question": "Early in a war, this president suspended habeas corpus along the rail route between Philadelphia and Washington. He delivered a roughly two-minute address at a (*) battlefield cemetery in Pennsylvania. For 10 points, name this president who issued the Emancipation Proclamation and was shot by John Wilkes Booth.",
     "answer": "Abraham <b><u>Lincoln</u></b>",
     "category": "History",
     "subcategory": "American History"
    },
    {
     "question": "Euclid proved there are infinitely many of these numbers by multiplying a finite list of them and adding one. The sieve of (*) Eratosthenes finds them, and every integer greater than one factors uniquely into them. For 10 points, name these numbers divisible only by one and themselves.",
     "answer": "<b><u>prime</u></b> numbers",
     "category": "Science",
     "subcategory": "Other Science"
    },
    {
     "question": "This composer dedicated, then furiously un-dedicated, his third symphony to Napoleon. He premiered his ninth symphony while (*) profoundly deaf, turning around to see the applause he could not hear. For 10 points, name this German composer of the Ode to Joy and a famous fifth symphony.",
     "answer": "Ludwig van <b><u>Beethoven</u></b>",
     "category": "Fine Arts",
     "subcategory": "Auditory Fine Arts"
    },
    {
     "question": "This figure took the form of a mare to distract a builder's stallion, later giving birth to the eight-legged horse Sleipnir. He engineered the death of (*) Baldr with a mistletoe dart, and he fathered Fenrir and the world serpent. For 10 points, name this Norse trickster god.",
     "answer": "<b><u>Loki</u></b>",
     "category": "Mythology",
     "subcategory": ""
    },
    {
     "question": "This thinker described a pin factory to illustrate the division of labor. He argued that self-interested actors are guided as if by an (*) invisible hand toward the public good. For 10 points, name this Scottish economist who wrote The Wealth of Nations.",
     "answer": "Adam <b><u>Smith</u></b>",
     "category": "Social Science",
     "subcategory": ""
    },
    {
     "question": "Laurens Coster of Haarlem is a disputed claimant to this invention, whose European debut produced a forty-two-line Bible. Its inventor adapted a (*) screw press and cast movable metal type. For 10 points, name this device introduced by Johannes Gutenberg that mechanized book production.",
     "answer": "<b><u>printing press</u></b> [accept <b><u>movable type</u></b>]",
     "category": "Other Academic",
     "subcategory": ""
    }
   ],
   "bonuses": [
    {
     "leadin": "This epic's hero blinds the cyclops Polyphemus. For 10 points each:",
     "parts": [
      "Name this Greek epic about a long journey home from Troy.",
      "The Odyssey is attributed to this blind poet, also credited with the Iliad.",
      "This faithful wife of Odysseus weaves and unweaves a shroud to put off her suitors."
     ],
     "answers": [
      "the <b><u>Odyssey</u></b>",
      "<b><u>Homer</u></b>",
      "<b><u>Penelope</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Literature",
     "subcategory": "European Literature"
    },
    {
     "leadin": "The Iron Curtain speech announced this conflict's battle lines. For 10 points each:",
     "parts": [
      "Name this decades-long standoff between the United States and the Soviet Union.",
      "The Cold War nearly turned hot during this 1962 crisis over Soviet weapons in the Caribbean.",
      "In this 1948 to 1949 operation, Western planes supplied a blockaded city with food and coal."
     ],
     "answers": [
      "<b><u>Cold War</u></b>",
      "<b><u>Cuban Missile Crisis</u></b>",
      "<b><u>Berlin Airlift</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "History",
     "subcategory": "American History"
    },
    {
     "leadin": "Rosalind Franklin's Photo 51 helped reveal this molecule's structure. For 10 points each:",
     "parts": [
      "Name this molecule that stores genetic information.",
      "These two scientists published DNA's double-helix structure in 1953.",
      "In DNA, adenine pairs with this base."
     ],
     "answers": [
      "<b><u>DNA</u></b> [accept <b><u>deoxyribonucleic acid</u></b>]",
      "James <b><u>Watson</u></b> and Francis <b><u>Crick</u></b>",
      "<b><u>thymine</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Science",
     "subcategory": "Biology"
    },
    {
     "leadin": "Only about ten of this poet's nearly eighteen hundred poems were published in her lifetime. For 10 points each:",
     "parts": [
      "Name this reclusive poet of Amherst, Massachusetts.",
      "In one Dickinson poem, this personified figure kindly stopped for me in a carriage.",
      "Dickinson wrote that this thing is the thing with feathers that perches in the soul."
     ],
     "answers": [
      "Emily <b><u>Dickinson</u></b>",
      "<b><u>Death</u></b>",
      "<b><u>hope</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Literature",
     "subcategory": "American Literature"
    },
    {
     "leadin": "This civilization mummified its dead for the journey to the afterlife. For 10 points each:",
     "parts": [
      "Name this North African civilization along a great river.",
      "This boy king's nearly intact tomb was found by Howard Carter in 1922.",
      "This stone, inscribed in three scripts, allowed Champollion to decipher hieroglyphs."
     ],
     "answers": [
      "ancient <b><u>Egypt</u></b>",
      "<b><u>Tutankhamun</u></b> [accept King <b><u>Tut</u></b>]",
      "<b><u>Rosetta Stone</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "History",
     "subcategory": "Ancient History"
    },
    {
     "leadin": "An apocryphal falling apple inspired this scientist's theory of gravity. For 10 points each:",
     "parts": [
      "Name this English physicist who formulated three laws of motion.",
      "Newton's second law states that force equals mass times this quantity.",
      "Newton and Leibniz independently invented this branch of mathematics."
     ],
     "answers": [
      "Isaac <b><u>Newton</u></b>",
      "<b><u>acceleration</u></b>",
      "<b><u>calculus</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Science",
     "subcategory": "Physics"
    },
    {
     "leadin": "A bus accident at age eighteen left this painter in lifelong pain. For 10 points each:",
     "parts": [
      "Name this Mexican painter of The Two Fridas.",
      "Kahlo is best known for many works in this genre, which depict the artist herself.",
      "Kahlo married this Mexican muralist, whose works include Man at the Crossroads."
     ],
     "answers": [
      "Frida <b><u>Kahlo</u></b>",
      "<b><u>self-portrait</u></b>s",
      "Diego <b><u>Rivera</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Fine Arts",
     "subcategory": "Visual Fine Arts"
    },
    {
     "leadin": "Souls crossed the river Styx to reach this realm. For 10 points each:",
     "parts": [
      "Name this Greek underworld, or the god who rules it.",
      "This three-headed dog guards the entrance to the underworld.",
      "This musician nearly retrieved his wife Eurydice from the underworld but looked back too soon."
     ],
     "answers": [
      "<b><u>Hades</u></b>",
      "<b><u>Cerberus</u></b>",
      "<b><u>Orpheus</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Mythology",
     "subcategory": ""
    },
    {
     "leadin": "Dogs salivated at the sound of a bell in this scientist's experiments. For 10 points each:",
     "parts": [
      "Name this Russian physiologist.",
      "Pavlov's work demonstrated this type of learning, in which a neutral stimulus becomes tied to a reflex.",
      "This American behaviorist studied operant conditioning using namesake boxes."
     ],
     "answers": [
      "Ivan <b><u>Pavlov</u></b>",
      "<b><u>classical conditioning</u></b> [prompt on conditioning]",
      "B. F. <b><u>Skinner</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Social Science",
     "subcategory": ""
    },
    {
     "leadin": "About half the world's population speaks a language from this family. For 10 points each:",
     "parts": [
      "Name this language family that includes English, Hindi, and Russian.",
      "The reconstructed ancestor of the family is abbreviated PIE, short for this name.",
      "This Romance language is the most spoken native language in South America."
     ],
     "answers": [
      "<b><u>Indo-European</u></b>",
      "<b><u>Proto-Indo-European</u></b>",
      "<b><u>Portuguese</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Other Academic",
     "subcategory": ""
    }
   ]
  },
  "3": {
   "name": "Demo Packet 3",
   "tossups": [
    {
     "question": "In this novel, children roll inside a tire into the yard of a reclusive neighbor who leaves gifts in a tree knothole. Its narrator watches her father (*) defend Tom Robinson, and Boo Radley saves her from Bob Ewell. For 10 points, name this Harper Lee novel narrated by Scout Finch.",
     "answer": "<b><u>To Kill a Mockingbird</u></b>",
     "category": "Literature",
     "subcategory": "American Literature"
    },
    {
     "question": "Conrad Schumann leapt over barbed wire days after this structure began going up in August 1961. Its crossings included (*) Checkpoint Charlie, and Ronald Reagan demanded that Mr. Gorbachev tear it down. For 10 points, name this barrier that divided a German city until 1989.",
     "answer": "<b><u>Berlin Wall</u></b>",
     "category": "History",
     "subcategory": "European History"
    },
    {
     "question": "The no-hair theorem says these objects are fully described by mass, charge, and spin. Light cannot escape from within their (*) event horizons, and one at the center of the galaxy M87 was imaged in 2019. For 10 points, name these objects formed when massive stars collapse.",
     "answer": "<b><u>black hole</u></b>s",
     "category": "Science",
     "subcategory": "Physics"
    },
    {
     "question": "In this novel, workers at the Ministry of Truth drop old newspaper articles down memory holes. Its protagonist is tortured with a cage of (*) rats in Room 101 and betrays his lover Julia. For 10 points, name this dystopian George Orwell novel starring Winston Smith.",
     "answer": "<b><u>1984</u></b> [accept <b><u>Nineteen Eighty-Four</u></b>]",
     "category": "Literature",
     "subcategory": "British Literature"
    },
    {
     "question": "Sogdian merchants dominated trade along this network, whose eastern terminus was often the city of Chang'an. Marco Polo traveled it, and (*) paper, gunpowder, and plague all moved west along it. For 10 points, name this network of routes that carried a luxury fabric out of China.",
     "answer": "<b><u>Silk Road</u></b> [accept <b><u>Silk Route</u></b>s]",
     "category": "History",
     "subcategory": "World History"
    },
    {
     "question": "Joseph Priestley isolated this element by heating mercuric oxide and called it dephlogisticated air. Antoine (*) Lavoisier named it, wrongly believing it appeared in all acids. For 10 points, name this element, about 21 percent of the atmosphere, needed for combustion and breathing.",
     "answer": "<b><u>oxygen</u></b>",
     "category": "Science",
     "subcategory": "Chemistry"
    },
    {
     "question": "This artist painted his own flayed skin held by Saint Bartholomew in a fresco of the Last Judgment. He carved a Pieta at twenty-four and painted (*) God reaching toward Adam on a chapel ceiling. For 10 points, name this sculptor of David who painted the Sistine Chapel.",
     "answer": "<b><u>Michelangelo</u></b> Buonarroti",
     "category": "Fine Arts",
     "subcategory": "Visual Fine Arts"
    },
    {
     "question": "This philosopher's Symposium presents love as a ladder ascending toward beauty itself. In one work, he described prisoners who mistake (*) shadows on a cave wall for reality, and his Republic imagines philosopher-kings. For 10 points, name this student of Socrates and teacher of Aristotle.",
     "answer": "<b><u>Plato</u></b>",
     "category": "Philosophy",
     "subcategory": ""
    },
    {
     "question": "This country's four main islands include Shikoku and Kyushu. Its highest peak, a snow-capped (*) volcano, appears in a famous series of woodblock prints by Hokusai. For 10 points, name this island nation with capital Tokyo.",
     "answer": "<b><u>Japan</u></b>",
     "category": "Geography",
     "subcategory": ""
    },
    {
     "question": "This athlete hit The Shot over Craig Ehlo in 1989 and later scored 38 points in the Flu Game. He won six championships with the (*) Chicago Bulls, twice retiring, once to play minor-league baseball. For 10 points, name this basketball great who wore number 23.",
     "answer": "Michael <b><u>Jordan</u></b>",
     "category": "Trash",
     "subcategory": ""
    }
   ],
   "bonuses": [
    {
     "leadin": "This poet's Twenty Love Poems and a Song of Despair made him famous at nineteen. For 10 points each:",
     "parts": [
      "Name this Chilean poet.",
      "Neruda won this international prize for literature in 1971.",
      "Neruda's Canto General is an epic history of this continent."
     ],
     "answers": [
      "Pablo <b><u>Neruda</u></b>",
      "<b><u>Nobel</u></b> Prize in Literature",
      "South <b><u>America</u></b> [accept the <b><u>Americas</u></b>]"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Literature",
     "subcategory": "World Literature"
    },
    {
     "leadin": "The assassination of Franz Ferdinand sparked this conflict. For 10 points each:",
     "parts": [
      "Name this war fought from 1914 to 1918.",
      "This form of combat defined the Western Front, with lines stretching from the Channel to Switzerland.",
      "This 1919 treaty ended the war with Germany and assigned it war guilt."
     ],
     "answers": [
      "<b><u>World War I</u></b> [accept the <b><u>Great War</u></b> or <b><u>First World War</u></b>]",
      "<b><u>trench</u></b> warfare",
      "Treaty of <b><u>Versailles</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "History",
     "subcategory": "European History"
    },
    {
     "leadin": "Finches of the Galapagos Islands helped inspire this theory. For 10 points each:",
     "parts": [
      "Name this theory that species change over time through natural selection.",
      "This naturalist proposed natural selection in On the Origin of Species.",
      "Darwin announced the theory jointly with this naturalist, who reached similar conclusions in the Malay Archipelago."
     ],
     "answers": [
      "<b><u>evolution</u></b>",
      "Charles <b><u>Darwin</u></b>",
      "Alfred Russel <b><u>Wallace</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Science",
     "subcategory": "Biology"
    },
    {
     "leadin": "This playwright's Theban plays follow one doomed family. For 10 points each:",
     "parts": [
      "Name this Greek tragedian.",
      "In this Sophocles play, the title king discovers he has killed his father and married his mother.",
      "In this play, Oedipus's daughter defies Creon to bury her brother Polynices."
     ],
     "answers": [
      "<b><u>Sophocles</u></b>",
      "<b><u>Oedipus Rex</u></b> [accept <b><u>Oedipus the King</u></b> or <b><u>Oedipus Tyrannus</u></b>]",
      "<b><u>Antigone</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Literature",
     "subcategory": "European Literature"
    },
    {
     "leadin": "A bus boycott in Montgomery began after one woman kept her seat. For 10 points each:",
     "parts": [
      "Name this seamstress arrested in 1955.",
      "The boycott elevated this minister, who later delivered the I Have a Dream speech.",
      "This 1954 Supreme Court case declared school segregation unconstitutional."
     ],
     "answers": [
      "Rosa <b><u>Parks</u></b>",
      "Martin Luther <b><u>King</u></b> Jr.",
      "<b><u>Brown</u></b> v. Board of Education"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "History",
     "subcategory": "American History"
    },
    {
     "leadin": "The 1883 eruption of Krakatoa was heard thousands of miles away. For 10 points each:",
     "parts": [
      "Name these geological features that erupt molten rock.",
      "Most of the world's volcanoes lie along this seismically active belt around an ocean.",
      "Before it erupts, molten rock underground is called this."
     ],
     "answers": [
      "<b><u>volcano</u></b>es",
      "<b><u>Ring of Fire</u></b> [accept Pacific <b><u>Ring of Fire</u></b>]",
      "<b><u>magma</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Science",
     "subcategory": "Other Science"
    },
    {
     "leadin": "This composer wrote his first symphony at eight years old. For 10 points each:",
     "parts": [
      "Name this Austrian composer of Eine kleine Nachtmusik.",
      "In this Mozart opera, the Queen of the Night sings a famously high aria and Papageno catches birds.",
      "Mozart left this final Mass setting unfinished at his death in 1791."
     ],
     "answers": [
      "Wolfgang Amadeus <b><u>Mozart</u></b>",
      "The <b><u>Magic Flute</u></b> [accept Die <b><u>Zauberflote</u></b>]",
      "<b><u>Requiem</u></b> in D minor"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Fine Arts",
     "subcategory": "Auditory Fine Arts"
    },
    {
     "leadin": "The phrase existence precedes essence summarizes this movement. For 10 points each:",
     "parts": [
      "Name this twentieth-century philosophical movement.",
      "This French existentialist wrote Being and Nothingness and declined the Nobel Prize.",
      "Sartre's partner, this philosopher, wrote the feminist landmark The Second Sex."
     ],
     "answers": [
      "<b><u>existentialism</u></b>",
      "Jean-Paul <b><u>Sartre</u></b>",
      "Simone de <b><u>Beauvoir</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Philosophy",
     "subcategory": ""
    },
    {
     "leadin": "This river's annual floods deposit fertile silt across northern India. For 10 points each:",
     "parts": [
      "Name this river sacred in Hinduism, which flows past Varanasi.",
      "This longest river of Asia flows through the Three Gorges Dam.",
      "This Southeast Asian river forms much of the Thailand-Laos border before its delta in Vietnam."
     ],
     "answers": [
      "<b><u>Ganges</u></b> River [accept <b><u>Ganga</u></b>]",
      "<b><u>Yangtze</u></b> River [accept <b><u>Chang Jiang</u></b>]",
      "<b><u>Mekong</u></b> River"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Geography",
     "subcategory": ""
    },
    {
     "leadin": "This character debuted as Jumpman in the arcade game Donkey Kong. For 10 points each:",
     "parts": [
      "Name this mustachioed Nintendo plumber.",
      "Mario's chief antagonist is this fire-breathing Koopa king.",
      "This Mario spin-off series puts the cast in go-karts, throwing shells at one another."
     ],
     "answers": [
      "<b><u>Mario</u></b>",
      "<b><u>Bowser</u></b>",
      "<b><u>Mario Kart</u></b>"
     ],
     "values": [
      10,
      10,
      10
     ],
     "category": "Trash",
     "subcategory": ""
    }
   ]
  }
 },
 "roster": {
  "version": "2.1.1",
  "objects": [
   {
    "type": "Tournament",
    "name": "Demo Tournament",
    "registrations": [
     {
      "name": "Summit",
      "teams": [
       {
        "name": "Summit",
        "players": [
         {
          "name": "Ada"
         },
         {
          "name": "Boris"
         },
         {
          "name": "Camille"
         },
         {
          "name": "Dev"
         }
        ]
       }
      ]
     },
     {
      "name": "Riverside",
      "teams": [
       {
        "name": "Riverside",
        "players": [
         {
          "name": "Elena"
         },
         {
          "name": "Farid"
         },
         {
          "name": "Grace"
         },
         {
          "name": "Hugo"
         }
        ]
       }
      ]
     },
     {
      "name": "Maple Grove",
      "teams": [
       {
        "name": "Maple Grove",
        "players": [
         {
          "name": "Iris"
         },
         {
          "name": "Jonah"
         },
         {
          "name": "Kira"
         }
        ]
       }
      ]
     },
     {
      "name": "Harbor View",
      "teams": [
       {
        "name": "Harbor View",
        "players": [
         {
          "name": "Leo"
         },
         {
          "name": "Mina"
         },
         {
          "name": "Noor"
         }
        ]
       }
      ]
     }
    ]
   }
  ]
 },
 "schedule": {
  "v": 1,
  "rooms": [
   {
    "name": "Room A",
    "bucket": null
   },
   {
    "name": "Room B",
    "bucket": null
   }
  ],
  "phases": [
   {
    "name": "Round robin",
    "rounds": [
     {
      "round": 1,
      "games": [
       {
        "room": 0,
        "a": {
         "team": "Riverside"
        },
        "b": {
         "team": "Maple Grove"
        }
       },
       {
        "room": 1,
        "a": {
         "team": "Summit"
        },
        "b": {
         "team": "Harbor View"
        }
       }
      ],
      "byes": []
     },
     {
      "round": 2,
      "games": [
       {
        "room": 0,
        "a": {
         "team": "Riverside"
        },
        "b": {
         "team": "Harbor View"
        }
       },
       {
        "room": 1,
        "a": {
         "team": "Summit"
        },
        "b": {
         "team": "Maple Grove"
        }
       }
      ],
      "byes": []
     },
     {
      "round": 3,
      "games": [
       {
        "room": 0,
        "a": {
         "team": "Riverside"
        },
        "b": {
         "team": "Summit"
        }
       },
       {
        "room": 1,
        "a": {
         "team": "Maple Grove"
        },
        "b": {
         "team": "Harbor View"
        }
       }
      ],
      "byes": []
     }
    ]
   }
  ],
  "pools": {},
  "updated": 1753500000000
 },
 "catmap": {
  "rounds": {
   "1": {
    "t": [
     {
      "c": "Literature",
      "s": "American Literature"
     },
     {
      "c": "History",
      "s": "European History"
     },
     {
      "c": "Science",
      "s": "Physics"
     },
     {
      "c": "Literature",
      "s": "British Literature"
     },
     {
      "c": "History",
      "s": "American History"
     },
     {
      "c": "Science",
      "s": "Biology"
     },
     {
      "c": "Fine Arts",
      "s": "Visual Fine Arts"
     },
     {
      "c": "Religion",
      "s": ""
     },
     {
      "c": "Geography",
      "s": ""
     },
     {
      "c": "Trash",
      "s": ""
     }
    ],
    "b": [
     {
      "c": "Literature",
      "s": "World Literature"
     },
     {
      "c": "History",
      "s": "Ancient History"
     },
     {
      "c": "Science",
      "s": "Chemistry"
     },
     {
      "c": "Literature",
      "s": "British Literature"
     },
     {
      "c": "History",
      "s": "European History"
     },
     {
      "c": "Science",
      "s": "Other Science"
     },
     {
      "c": "Fine Arts",
      "s": "Visual Fine Arts"
     },
     {
      "c": "Religion",
      "s": ""
     },
     {
      "c": "Geography",
      "s": ""
     },
     {
      "c": "Trash",
      "s": ""
     }
    ]
   },
   "2": {
    "t": [
     {
      "c": "Literature",
      "s": "World Literature"
     },
     {
      "c": "History",
      "s": "World History"
     },
     {
      "c": "Science",
      "s": "Chemistry"
     },
     {
      "c": "Literature",
      "s": "European Literature"
     },
     {
      "c": "History",
      "s": "American History"
     },
     {
      "c": "Science",
      "s": "Other Science"
     },
     {
      "c": "Fine Arts",
      "s": "Auditory Fine Arts"
     },
     {
      "c": "Mythology",
      "s": ""
     },
     {
      "c": "Social Science",
      "s": ""
     },
     {
      "c": "Other Academic",
      "s": ""
     }
    ],
    "b": [
     {
      "c": "Literature",
      "s": "European Literature"
     },
     {
      "c": "History",
      "s": "American History"
     },
     {
      "c": "Science",
      "s": "Biology"
     },
     {
      "c": "Literature",
      "s": "American Literature"
     },
     {
      "c": "History",
      "s": "Ancient History"
     },
     {
      "c": "Science",
      "s": "Physics"
     },
     {
      "c": "Fine Arts",
      "s": "Visual Fine Arts"
     },
     {
      "c": "Mythology",
      "s": ""
     },
     {
      "c": "Social Science",
      "s": ""
     },
     {
      "c": "Other Academic",
      "s": ""
     }
    ]
   },
   "3": {
    "t": [
     {
      "c": "Literature",
      "s": "American Literature"
     },
     {
      "c": "History",
      "s": "European History"
     },
     {
      "c": "Science",
      "s": "Physics"
     },
     {
      "c": "Literature",
      "s": "British Literature"
     },
     {
      "c": "History",
      "s": "World History"
     },
     {
      "c": "Science",
      "s": "Chemistry"
     },
     {
      "c": "Fine Arts",
      "s": "Visual Fine Arts"
     },
     {
      "c": "Philosophy",
      "s": ""
     },
     {
      "c": "Geography",
      "s": ""
     },
     {
      "c": "Trash",
      "s": ""
     }
    ],
    "b": [
     {
      "c": "Literature",
      "s": "World Literature"
     },
     {
      "c": "History",
      "s": "European History"
     },
     {
      "c": "Science",
      "s": "Biology"
     },
     {
      "c": "Literature",
      "s": "European Literature"
     },
     {
      "c": "History",
      "s": "American History"
     },
     {
      "c": "Science",
      "s": "Other Science"
     },
     {
      "c": "Fine Arts",
      "s": "Auditory Fine Arts"
     },
     {
      "c": "Philosophy",
      "s": ""
     },
     {
      "c": "Geography",
      "s": ""
     },
     {
      "c": "Trash",
      "s": ""
     }
    ]
   }
  }
 },
 "entries": [
  {
   "id": 1,
   "round": 1,
   "room": "Room A",
   "filename": "Round_1_Riverside_Maple_Grove.qbtd.json",
   "qbj": {
    "tossups_read": 10,
    "match_teams": [
     {
      "bonus_points": 90,
      "lineups": [
       {
        "first_question": 1,
        "players": [
         {
          "name": "Elena"
         },
         {
          "name": "Farid"
         },
         {
          "name": "Grace"
         },
         {
          "name": "Hugo"
         }
        ]
       }
      ],
      "match_players": [
       {
        "player": {
         "name": "Elena"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 1
         },
         {
          "answer": {
           "value": 15
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Farid"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Grace"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 1
         },
         {
          "answer": {
           "value": 15
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Hugo"
        },
        "answer_counts": [],
        "tossups_heard": 10
       }
      ],
      "team": {
       "name": "Riverside",
       "players": [
        {
         "name": "Elena"
        },
        {
         "name": "Farid"
        },
        {
         "name": "Grace"
        },
        {
         "name": "Hugo"
        }
       ]
      }
     },
     {
      "bonus_points": 70,
      "lineups": [
       {
        "first_question": 1,
        "players": [
         {
          "name": "Iris"
         },
         {
          "name": "Jonah"
         },
         {
          "name": "Kira"
         }
        ]
       }
      ],
      "match_players": [
       {
        "player": {
         "name": "Iris"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Jonah"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 2
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Kira"
        },
        "answer_counts": [],
        "tossups_heard": 10
       }
      ],
      "team": {
       "name": "Maple Grove",
       "players": [
        {
         "name": "Iris"
        },
        {
         "name": "Jonah"
        },
        {
         "name": "Kira"
        }
       ]
      }
     }
    ],
    "match_questions": [
     {
      "question_number": 1,
      "buzzes": [],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 1
      }
     },
     {
      "question_number": 2,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 24
        },
        "player": {
         "name": "Iris"
        },
        "team": {
         "name": "Maple Grove",
         "players": [
          {
           "name": "Iris"
          },
          {
           "name": "Jonah"
          },
          {
           "name": "Kira"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 2
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 2
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 3,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 21
        },
        "player": {
         "name": "Elena"
        },
        "team": {
         "name": "Riverside",
         "players": [
          {
           "name": "Elena"
          },
          {
           "name": "Farid"
          },
          {
           "name": "Grace"
          },
          {
           "name": "Hugo"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 3
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 3
       },
       "parts": [
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 4,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 21
        },
        "player": {
         "name": "Elena"
        },
        "team": {
         "name": "Riverside",
         "players": [
          {
           "name": "Elena"
          },
          {
           "name": "Farid"
          },
          {
           "name": "Grace"
          },
          {
           "name": "Hugo"
          }
         ]
        },
        "result": {
         "value": 15
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 4
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 4
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 5,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 30
        },
        "player": {
         "name": "Farid"
        },
        "team": {
         "name": "Riverside",
         "players": [
          {
           "name": "Elena"
          },
          {
           "name": "Farid"
          },
          {
           "name": "Grace"
          },
          {
           "name": "Hugo"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 5
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 5
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 6,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 25
        },
        "player": {
         "name": "Jonah"
        },
        "team": {
         "name": "Maple Grove",
         "players": [
          {
           "name": "Iris"
          },
          {
           "name": "Jonah"
          },
          {
           "name": "Kira"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 6
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 6
       },
       "parts": [
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 7,
      "buzzes": [],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 7
      }
     },
     {
      "question_number": 8,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 21
        },
        "player": {
         "name": "Grace"
        },
        "team": {
         "name": "Riverside",
         "players": [
          {
           "name": "Elena"
          },
          {
           "name": "Farid"
          },
          {
           "name": "Grace"
          },
          {
           "name": "Hugo"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 8
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 8
       },
       "parts": [
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 9,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 17
        },
        "player": {
         "name": "Grace"
        },
        "team": {
         "name": "Riverside",
         "players": [
          {
           "name": "Elena"
          },
          {
           "name": "Farid"
          },
          {
           "name": "Grace"
          },
          {
           "name": "Hugo"
          }
         ]
        },
        "result": {
         "value": 15
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 9
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 9
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 10,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 29
        },
        "player": {
         "name": "Jonah"
        },
        "team": {
         "name": "Maple Grove",
         "players": [
          {
           "name": "Iris"
          },
          {
           "name": "Jonah"
          },
          {
           "name": "Kira"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 10
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 10
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        }
       ]
      }
     }
    ],
    "_round": 1
   }
  },
  {
   "id": 2,
   "round": 1,
   "room": "Room B",
   "filename": "Round_1_Summit_Harbor_View.qbtd.json",
   "qbj": {
    "tossups_read": 10,
    "match_teams": [
     {
      "bonus_points": 160,
      "lineups": [
       {
        "first_question": 1,
        "players": [
         {
          "name": "Ada"
         },
         {
          "name": "Boris"
         },
         {
          "name": "Camille"
         },
         {
          "name": "Dev"
         }
        ]
       }
      ],
      "match_players": [
       {
        "player": {
         "name": "Ada"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 4
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Boris"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 2
         },
         {
          "answer": {
           "value": 15
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Camille"
        },
        "answer_counts": [
         {
          "answer": {
           "value": -5
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Dev"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       }
      ],
      "team": {
       "name": "Summit",
       "players": [
        {
         "name": "Ada"
        },
        {
         "name": "Boris"
        },
        {
         "name": "Camille"
        },
        {
         "name": "Dev"
        }
       ]
      }
     },
     {
      "bonus_points": 10,
      "lineups": [
       {
        "first_question": 1,
        "players": [
         {
          "name": "Leo"
         },
         {
          "name": "Mina"
         },
         {
          "name": "Noor"
         }
        ]
       }
      ],
      "match_players": [
       {
        "player": {
         "name": "Leo"
        },
        "answer_counts": [],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Mina"
        },
        "answer_counts": [],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Noor"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       }
      ],
      "team": {
       "name": "Harbor View",
       "players": [
        {
         "name": "Leo"
        },
        {
         "name": "Mina"
        },
        {
         "name": "Noor"
        }
       ]
      }
     }
    ],
    "match_questions": [
     {
      "question_number": 1,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 39
        },
        "player": {
         "name": "Dev"
        },
        "team": {
         "name": "Summit",
         "players": [
          {
           "name": "Ada"
          },
          {
           "name": "Boris"
          },
          {
           "name": "Camille"
          },
          {
           "name": "Dev"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 1
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 1
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 2,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 21
        },
        "player": {
         "name": "Boris"
        },
        "team": {
         "name": "Summit",
         "players": [
          {
           "name": "Ada"
          },
          {
           "name": "Boris"
          },
          {
           "name": "Camille"
          },
          {
           "name": "Dev"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 2
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 2
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 3,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 24
        },
        "player": {
         "name": "Noor"
        },
        "team": {
         "name": "Harbor View",
         "players": [
          {
           "name": "Leo"
          },
          {
           "name": "Mina"
          },
          {
           "name": "Noor"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 3
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 3
       },
       "parts": [
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 4,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 25
        },
        "player": {
         "name": "Ada"
        },
        "team": {
         "name": "Summit",
         "players": [
          {
           "name": "Ada"
          },
          {
           "name": "Boris"
          },
          {
           "name": "Camille"
          },
          {
           "name": "Dev"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 4
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 4
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 5,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 20
        },
        "player": {
         "name": "Boris"
        },
        "team": {
         "name": "Summit",
         "players": [
          {
           "name": "Ada"
          },
          {
           "name": "Boris"
          },
          {
           "name": "Camille"
          },
          {
           "name": "Dev"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 5
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 5
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 6,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 25
        },
        "player": {
         "name": "Ada"
        },
        "team": {
         "name": "Summit",
         "players": [
          {
           "name": "Ada"
          },
          {
           "name": "Boris"
          },
          {
           "name": "Camille"
          },
          {
           "name": "Dev"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 6
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 6
       },
       "parts": [
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 7,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 23
        },
        "player": {
         "name": "Ada"
        },
        "team": {
         "name": "Summit",
         "players": [
          {
           "name": "Ada"
          },
          {
           "name": "Boris"
          },
          {
           "name": "Camille"
          },
          {
           "name": "Dev"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 7
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 7
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 8,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 20
        },
        "player": {
         "name": "Ada"
        },
        "team": {
         "name": "Summit",
         "players": [
          {
           "name": "Ada"
          },
          {
           "name": "Boris"
          },
          {
           "name": "Camille"
          },
          {
           "name": "Dev"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 8
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 8
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 9,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 28
        },
        "player": {
         "name": "Camille"
        },
        "team": {
         "name": "Summit",
         "players": [
          {
           "name": "Ada"
          },
          {
           "name": "Boris"
          },
          {
           "name": "Camille"
          },
          {
           "name": "Dev"
          }
         ]
        },
        "result": {
         "value": -5
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 9
      }
     },
     {
      "question_number": 10,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 21
        },
        "player": {
         "name": "Boris"
        },
        "team": {
         "name": "Summit",
         "players": [
          {
           "name": "Ada"
          },
          {
           "name": "Boris"
          },
          {
           "name": "Camille"
          },
          {
           "name": "Dev"
          }
         ]
        },
        "result": {
         "value": 15
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 10
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 10
       },
       "parts": [
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 10
        }
       ]
      }
     }
    ],
    "_round": 1
   }
  },
  {
   "id": 3,
   "round": 2,
   "room": "Room A",
   "filename": "Round_2_Riverside_Harbor_View.qbtd.json",
   "qbj": {
    "tossups_read": 10,
    "match_teams": [
     {
      "bonus_points": 140,
      "lineups": [
       {
        "first_question": 1,
        "players": [
         {
          "name": "Elena"
         },
         {
          "name": "Farid"
         },
         {
          "name": "Grace"
         },
         {
          "name": "Hugo"
         }
        ]
       }
      ],
      "match_players": [
       {
        "player": {
         "name": "Elena"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 3
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Farid"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Grace"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Hugo"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       }
      ],
      "team": {
       "name": "Riverside",
       "players": [
        {
         "name": "Elena"
        },
        {
         "name": "Farid"
        },
        {
         "name": "Grace"
        },
        {
         "name": "Hugo"
        }
       ]
      }
     },
     {
      "bonus_points": 60,
      "lineups": [
       {
        "first_question": 1,
        "players": [
         {
          "name": "Leo"
         },
         {
          "name": "Mina"
         },
         {
          "name": "Noor"
         }
        ]
       }
      ],
      "match_players": [
       {
        "player": {
         "name": "Leo"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 15
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Mina"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 2
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Noor"
        },
        "answer_counts": [],
        "tossups_heard": 10
       }
      ],
      "team": {
       "name": "Harbor View",
       "players": [
        {
         "name": "Leo"
        },
        {
         "name": "Mina"
        },
        {
         "name": "Noor"
        }
       ]
      }
     }
    ],
    "match_questions": [
     {
      "question_number": 1,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 21
        },
        "player": {
         "name": "Leo"
        },
        "team": {
         "name": "Harbor View",
         "players": [
          {
           "name": "Leo"
          },
          {
           "name": "Mina"
          },
          {
           "name": "Noor"
          }
         ]
        },
        "result": {
         "value": 15
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 1
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 1
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 2,
      "buzzes": [],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 2
      }
     },
     {
      "question_number": 3,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 26
        },
        "player": {
         "name": "Mina"
        },
        "team": {
         "name": "Harbor View",
         "players": [
          {
           "name": "Leo"
          },
          {
           "name": "Mina"
          },
          {
           "name": "Noor"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 3
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 3
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 4,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 28
        },
        "player": {
         "name": "Mina"
        },
        "team": {
         "name": "Harbor View",
         "players": [
          {
           "name": "Leo"
          },
          {
           "name": "Mina"
          },
          {
           "name": "Noor"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 4
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 4
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 5,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 33
        },
        "player": {
         "name": "Elena"
        },
        "team": {
         "name": "Riverside",
         "players": [
          {
           "name": "Elena"
          },
          {
           "name": "Farid"
          },
          {
           "name": "Grace"
          },
          {
           "name": "Hugo"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 5
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 5
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 6,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 23
        },
        "player": {
         "name": "Elena"
        },
        "team": {
         "name": "Riverside",
         "players": [
          {
           "name": "Elena"
          },
          {
           "name": "Farid"
          },
          {
           "name": "Grace"
          },
          {
           "name": "Hugo"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 6
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 6
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 7,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 28
        },
        "player": {
         "name": "Grace"
        },
        "team": {
         "name": "Riverside",
         "players": [
          {
           "name": "Elena"
          },
          {
           "name": "Farid"
          },
          {
           "name": "Grace"
          },
          {
           "name": "Hugo"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 7
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 7
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 8,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 35
        },
        "player": {
         "name": "Farid"
        },
        "team": {
         "name": "Riverside",
         "players": [
          {
           "name": "Elena"
          },
          {
           "name": "Farid"
          },
          {
           "name": "Grace"
          },
          {
           "name": "Hugo"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 8
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 8
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 9,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 28
        },
        "player": {
         "name": "Elena"
        },
        "team": {
         "name": "Riverside",
         "players": [
          {
           "name": "Elena"
          },
          {
           "name": "Farid"
          },
          {
           "name": "Grace"
          },
          {
           "name": "Hugo"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 9
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 9
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 10,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 37
        },
        "player": {
         "name": "Hugo"
        },
        "team": {
         "name": "Riverside",
         "players": [
          {
           "name": "Elena"
          },
          {
           "name": "Farid"
          },
          {
           "name": "Grace"
          },
          {
           "name": "Hugo"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 10
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 10
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        }
       ]
      }
     }
    ],
    "_round": 2
   }
  },
  {
   "id": 4,
   "round": 2,
   "room": "Room B",
   "filename": "Round_2_Summit_Maple_Grove.qbtd.json",
   "qbj": {
    "tossups_read": 10,
    "match_teams": [
     {
      "bonus_points": 130,
      "lineups": [
       {
        "first_question": 1,
        "players": [
         {
          "name": "Ada"
         },
         {
          "name": "Boris"
         },
         {
          "name": "Camille"
         },
         {
          "name": "Dev"
         }
        ]
       }
      ],
      "match_players": [
       {
        "player": {
         "name": "Ada"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 15
          },
          "number": 1
         },
         {
          "answer": {
           "value": 10
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Boris"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 15
          },
          "number": 1
         },
         {
          "answer": {
           "value": 10
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Camille"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 2
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Dev"
        },
        "answer_counts": [],
        "tossups_heard": 10
       }
      ],
      "team": {
       "name": "Summit",
       "players": [
        {
         "name": "Ada"
        },
        {
         "name": "Boris"
        },
        {
         "name": "Camille"
        },
        {
         "name": "Dev"
        }
       ]
      }
     },
     {
      "bonus_points": 50,
      "lineups": [
       {
        "first_question": 1,
        "players": [
         {
          "name": "Iris"
         },
         {
          "name": "Jonah"
         },
         {
          "name": "Kira"
         }
        ]
       }
      ],
      "match_players": [
       {
        "player": {
         "name": "Iris"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 15
          },
          "number": 1
         },
         {
          "answer": {
           "value": -5
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Jonah"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Kira"
        },
        "answer_counts": [],
        "tossups_heard": 10
       }
      ],
      "team": {
       "name": "Maple Grove",
       "players": [
        {
         "name": "Iris"
        },
        {
         "name": "Jonah"
        },
        {
         "name": "Kira"
        }
       ]
      }
     }
    ],
    "match_questions": [
     {
      "question_number": 1,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 25
        },
        "player": {
         "name": "Boris"
        },
        "team": {
         "name": "Summit",
         "players": [
          {
           "name": "Ada"
          },
          {
           "name": "Boris"
          },
          {
           "name": "Camille"
          },
          {
           "name": "Dev"
          }
         ]
        },
        "result": {
         "value": 15
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 1
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 1
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 2,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 16
        },
        "player": {
         "name": "Iris"
        },
        "team": {
         "name": "Maple Grove",
         "players": [
          {
           "name": "Iris"
          },
          {
           "name": "Jonah"
          },
          {
           "name": "Kira"
          }
         ]
        },
        "result": {
         "value": 15
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 2
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 2
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 3,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 26
        },
        "player": {
         "name": "Jonah"
        },
        "team": {
         "name": "Maple Grove",
         "players": [
          {
           "name": "Iris"
          },
          {
           "name": "Jonah"
          },
          {
           "name": "Kira"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 3
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 3
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 4,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 23
        },
        "player": {
         "name": "Ada"
        },
        "team": {
         "name": "Summit",
         "players": [
          {
           "name": "Ada"
          },
          {
           "name": "Boris"
          },
          {
           "name": "Camille"
          },
          {
           "name": "Dev"
          }
         ]
        },
        "result": {
         "value": 15
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 4
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 4
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 5,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 27
        },
        "player": {
         "name": "Ada"
        },
        "team": {
         "name": "Summit",
         "players": [
          {
           "name": "Ada"
          },
          {
           "name": "Boris"
          },
          {
           "name": "Camille"
          },
          {
           "name": "Dev"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 5
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 5
       },
       "parts": [
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 6,
      "buzzes": [],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 6
      }
     },
     {
      "question_number": 7,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 29
        },
        "player": {
         "name": "Camille"
        },
        "team": {
         "name": "Summit",
         "players": [
          {
           "name": "Ada"
          },
          {
           "name": "Boris"
          },
          {
           "name": "Camille"
          },
          {
           "name": "Dev"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 7
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 7
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 8,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 32
        },
        "player": {
         "name": "Boris"
        },
        "team": {
         "name": "Summit",
         "players": [
          {
           "name": "Ada"
          },
          {
           "name": "Boris"
          },
          {
           "name": "Camille"
          },
          {
           "name": "Dev"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 8
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 8
       },
       "parts": [
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 9,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 35
        },
        "player": {
         "name": "Camille"
        },
        "team": {
         "name": "Summit",
         "players": [
          {
           "name": "Ada"
          },
          {
           "name": "Boris"
          },
          {
           "name": "Camille"
          },
          {
           "name": "Dev"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 9
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 9
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 10,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 22
        },
        "player": {
         "name": "Iris"
        },
        "team": {
         "name": "Maple Grove",
         "players": [
          {
           "name": "Iris"
          },
          {
           "name": "Jonah"
          },
          {
           "name": "Kira"
          }
         ]
        },
        "result": {
         "value": -5
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 10
      }
     }
    ],
    "_round": 2
   }
  },
  {
   "id": 5,
   "round": 3,
   "room": "Room B",
   "filename": "Round_3_Maple_Grove_Harbor_View.qbtd.json",
   "qbj": {
    "tossups_read": 10,
    "match_teams": [
     {
      "bonus_points": 70,
      "lineups": [
       {
        "first_question": 1,
        "players": [
         {
          "name": "Iris"
         },
         {
          "name": "Jonah"
         },
         {
          "name": "Kira"
         }
        ]
       }
      ],
      "match_players": [
       {
        "player": {
         "name": "Iris"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 2
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Jonah"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 1
         },
         {
          "answer": {
           "value": 15
          },
          "number": 2
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Kira"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 1
         }
        ],
        "tossups_heard": 10
       }
      ],
      "team": {
       "name": "Maple Grove",
       "players": [
        {
         "name": "Iris"
        },
        {
         "name": "Jonah"
        },
        {
         "name": "Kira"
        }
       ]
      }
     },
     {
      "bonus_points": 60,
      "lineups": [
       {
        "first_question": 1,
        "players": [
         {
          "name": "Leo"
         },
         {
          "name": "Mina"
         },
         {
          "name": "Noor"
         }
        ]
       }
      ],
      "match_players": [
       {
        "player": {
         "name": "Leo"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 10
          },
          "number": 2
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Mina"
        },
        "answer_counts": [
         {
          "answer": {
           "value": 15
          },
          "number": 1
         },
         {
          "answer": {
           "value": -5
          },
          "number": 2
         }
        ],
        "tossups_heard": 10
       },
       {
        "player": {
         "name": "Noor"
        },
        "answer_counts": [],
        "tossups_heard": 10
       }
      ],
      "team": {
       "name": "Harbor View",
       "players": [
        {
         "name": "Leo"
        },
        {
         "name": "Mina"
        },
        {
         "name": "Noor"
        }
       ]
      }
     }
    ],
    "match_questions": [
     {
      "question_number": 1,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 32
        },
        "player": {
         "name": "Leo"
        },
        "team": {
         "name": "Harbor View",
         "players": [
          {
           "name": "Leo"
          },
          {
           "name": "Mina"
          },
          {
           "name": "Noor"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 1
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 1
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 2,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 34
        },
        "player": {
         "name": "Jonah"
        },
        "team": {
         "name": "Maple Grove",
         "players": [
          {
           "name": "Iris"
          },
          {
           "name": "Jonah"
          },
          {
           "name": "Kira"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 2
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 2
       },
       "parts": [
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 3,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 19
        },
        "player": {
         "name": "Mina"
        },
        "team": {
         "name": "Harbor View",
         "players": [
          {
           "name": "Leo"
          },
          {
           "name": "Mina"
          },
          {
           "name": "Noor"
          }
         ]
        },
        "result": {
         "value": 15
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 3
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 3
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 4,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 28
        },
        "player": {
         "name": "Mina"
        },
        "team": {
         "name": "Harbor View",
         "players": [
          {
           "name": "Leo"
          },
          {
           "name": "Mina"
          },
          {
           "name": "Noor"
          }
         ]
        },
        "result": {
         "value": -5
        }
       },
       {
        "buzz_position": {
         "word_index": 37
        },
        "player": {
         "name": "Kira"
        },
        "team": {
         "name": "Maple Grove",
         "players": [
          {
           "name": "Iris"
          },
          {
           "name": "Jonah"
          },
          {
           "name": "Kira"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 4
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 4
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 5,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 27
        },
        "player": {
         "name": "Mina"
        },
        "team": {
         "name": "Harbor View",
         "players": [
          {
           "name": "Leo"
          },
          {
           "name": "Mina"
          },
          {
           "name": "Noor"
          }
         ]
        },
        "result": {
         "value": -5
        }
       },
       {
        "buzz_position": {
         "word_index": 30
        },
        "player": {
         "name": "Iris"
        },
        "team": {
         "name": "Maple Grove",
         "players": [
          {
           "name": "Iris"
          },
          {
           "name": "Jonah"
          },
          {
           "name": "Kira"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 5
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 5
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 6,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 28
        },
        "player": {
         "name": "Iris"
        },
        "team": {
         "name": "Maple Grove",
         "players": [
          {
           "name": "Iris"
          },
          {
           "name": "Jonah"
          },
          {
           "name": "Kira"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 6
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 6
       },
       "parts": [
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 7,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 23
        },
        "player": {
         "name": "Jonah"
        },
        "team": {
         "name": "Maple Grove",
         "players": [
          {
           "name": "Iris"
          },
          {
           "name": "Jonah"
          },
          {
           "name": "Kira"
          }
         ]
        },
        "result": {
         "value": 15
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 7
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 7
       },
       "parts": [
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 0
        },
        {
         "controlled_points": 10
        }
       ]
      }
     },
     {
      "question_number": 8,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 19
        },
        "player": {
         "name": "Jonah"
        },
        "team": {
         "name": "Maple Grove",
         "players": [
          {
           "name": "Iris"
          },
          {
           "name": "Jonah"
          },
          {
           "name": "Kira"
          }
         ]
        },
        "result": {
         "value": 15
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 8
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 8
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 9,
      "buzzes": [
       {
        "buzz_position": {
         "word_index": 26
        },
        "player": {
         "name": "Leo"
        },
        "team": {
         "name": "Harbor View",
         "players": [
          {
           "name": "Leo"
          },
          {
           "name": "Mina"
          },
          {
           "name": "Noor"
          }
         ]
        },
        "result": {
         "value": 10
        }
       }
      ],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 9
      },
      "bonus": {
       "question": {
        "parts": 3,
        "type": "bonus",
        "question_number": 9
       },
       "parts": [
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 10
        },
        {
         "controlled_points": 0
        }
       ]
      }
     },
     {
      "question_number": 10,
      "buzzes": [],
      "tossup_question": {
       "parts": 1,
       "type": "tossup",
       "question_number": 10
      }
     }
    ],
    "_round": 3
   }
  }
 ]
};
