// demo.js — the demo tournament's backend, entirely in the browser.
//
// api.js routes pub() here whenever the page opened with ?t=demo or
// ?b=demo (the slug and bucket secret 'demo' are reserved server-side),
// so the REAL pages — t.html, read.html, bucket.html — run unmodified
// against a committed fixture instead of the Worker, the same idea as the
// archive's useFrozenData. Unlike the archive, the demo is live: games a
// visitor reads in the embedded MODAQ upload into localStorage and flow
// into stats, buzzpoints, and categories exactly as at a real tournament.
//
// The fixture (app/demo/fixture.js, generated by tools/demo_fixture.mjs)
// holds rounds 1-2 played plus round 3's Room B game; the visitor's room
// is Room A, whose round-3 game — Riverside vs Summit, both 2-0 — decides
// the tournament. Reading and uploading it completes round 3, which also
// unlocks the round on the buzzpoints tab (the same every-room-is-done
// gate the Worker applies).
//
// Nothing here touches the network. Uploads live under one localStorage
// key; reset() clears them plus the reader's per-game stores.

import fixture from '../demo/fixture.js';
import { parseMatch, matchPayload } from '../engine/qbj.js';

const UPLOADS_KEY = 'qbtdDemoUploads';
const BUZZ_KEY = 'qbtdBuzzKey:demo'; // pubview's sessionStorage slot for slug 'demo'
const FIRST_LOCAL_ID = 1000; // sorts after every fixture id, so re-reads win dedupe

// Browser storage when present, in-memory otherwise (node tests; node's
// experimental localStorage global is method-less without a flag, so
// check capability, not existence).
const mem = new Map();
const usable = typeof localStorage !== 'undefined'
  && typeof localStorage.getItem === 'function'
  && typeof localStorage.removeItem === 'function'
  && typeof localStorage.key === 'function';
const local = usable ? localStorage : {
  getItem: (k) => (mem.has(k) ? mem.get(k) : null),
  setItem: (k, v) => mem.set(k, String(v)),
  removeItem: (k) => mem.delete(k),
  get length() { return mem.size; },
  key: (i) => [...mem.keys()][i],
};

function uploads() {
  try {
    const list = JSON.parse(local.getItem(UPLOADS_KEY));
    return Array.isArray(list) ? list : [];
  } catch (e) { return []; }
}

function saveUploads(list) {
  local.setItem(UPLOADS_KEY, JSON.stringify(list));
}

/** Clear everything the demo wrote: uploads, the reader's games, the
    buzzpoints unlock. */
export function reset() {
  local.removeItem(UPLOADS_KEY);
  const stale = [];
  for (let i = 0; i < local.length; i++) {
    const k = local.key(i);
    if (k && (k.startsWith('qbtdMeta:demo:') || k.startsWith('qbtdGame:demo:'))) stale.push(k);
  }
  for (const k of stale) local.removeItem(k);
  if (typeof sessionStorage !== 'undefined') sessionStorage.removeItem(BUZZ_KEY);
}

/* ---------- route helpers ---------- */

const err = (message) => { throw new Error(message); };

const roomName = () => fixture.rooms[fixture.readerRoom];

// Fixture games plus everything uploaded from this browser, in the
// public bundle's entry shape.
function allEntries() {
  return [
    ...fixture.entries,
    ...uploads().filter((u) => u.qbj && !u.error).map((u) => ({
      id: u.id, round: u.round, room: roomName(), filename: u.filename, qbj: u.qbj,
    })),
  ];
}

function scheduledGames(round) {
  for (const ph of fixture.schedule.phases) {
    for (const r of ph.rounds) if (r.round === round) return r.games.length;
  }
  return fixture.rooms.length;
}

// The Worker's rule: a round is done when every scheduled game is in.
function roundDone(round) {
  const rooms = new Set(allEntries().filter((e) => e.round === round).map((e) => e.room));
  return rooms.size >= scheduledGames(round);
}

const packetRounds = () => Object.keys(fixture.packets).map(Number).sort((x, y) => x - y);

function packetList() {
  return packetRounds().map((n) => ({ number: n, packet_name: fixture.packets[n].name + '.json' }));
}

function packetFor(round) {
  if (round > fixture.currentRound) err('not the live round yet');
  const p = fixture.packets[round];
  if (!p) err('no packet for round ' + round);
  return p;
}

/* ---------- the two route families ---------- */

function bucketState() {
  const list = uploads();
  return {
    tournament: fixture.name,
    room: roomName(),
    current_round: fixture.currentRound,
    closes: Date.now() + 48 * 3600 * 1000,
    packet: packetList().find((p) => p.number === fixture.currentRound) || null,
    packets: packetList(),
    roster: true,
    settings: fixture.settings,
    announce: [],
    uploads: [...list].reverse().map(({ qbj, ...u }) => u),
    upload_count: list.length,
  };
}

async function upload(query, opts) {
  const filename = query.get('name') || 'upload.qbj';
  let round = Number(query.get('round'));
  if (!Number.isInteger(round) || round < 1 || round > 999) round = fixture.currentRound;

  let body = opts && opts.body;
  if (body && typeof body !== 'string' && typeof body.text === 'function') body = await body.text();
  if (!body) err('empty file');

  const isMatch = /\.qbj$/i.test(filename) || /\.qbtd\.json$/i.test(filename);
  const kind = /\.qbj$/i.test(filename) ? 'qbj'
    : /\.qbtd\.json$/i.test(filename) ? 'combined'
      : /_game\.json$/i.test(filename) ? 'game' : 'other';
  let error = null;
  let qbj = null;
  if (isMatch) {
    try {
      qbj = matchPayload(JSON.parse(body));
      parseMatch(qbj, { filename });
    } catch (e) {
      error = e.message;
      qbj = null;
    }
  }

  const list = uploads();
  const id = list.reduce((n, u) => Math.max(n, u.id), FIRST_LOCAL_ID - 1) + 1;
  list.push({ id, round, kind, filename, size: body.length, error, created: Date.now(), qbj });
  saveUploads(list);
  return { id, filename, round, kind, error, announce: [] };
}

function pubState() {
  const entries = allEntries();
  const last = entries[entries.length - 1];
  return {
    name: fixture.name,
    current_round: fixture.currentRound,
    roster: true,
    announce: [],
    schedule: fixture.schedule.updated,
    // Truthy mode shows the tab; the sessionStorage key seeded below
    // stands in for the password a real tournament's viewers enter.
    buzz: 'demo',
    buzz_kdf: null,
    buzz_v: 'demo',
    buzz_done: packetRounds().filter(roundDone),
    packet_rounds: packetRounds(),
    cats: 1,
    version: (last ? last.id : 0) + ':' + entries.length,
    files: entries.map(({ qbj, ...f }) => f),
  };
}

/* ---------- the pub() entry point ---------- */

/** Handle one api.js pub() call. Same success values and thrown
    user-facing errors as the Worker routes it stands in for. */
export async function demoPub(path, opts = {}) {
  const q = path.indexOf('?');
  const p = q < 0 ? path : path.slice(0, q);
  const query = new URLSearchParams(q < 0 ? '' : path.slice(q + 1));
  const round = Number(query.get('round'));

  switch (p) {
    case '/b/demo': return bucketState();
    case '/b/demo/packet': return packetFor(Number.isInteger(round) && round >= 1 ? round : fixture.currentRound);
    case '/b/demo/roster': return fixture.roster;
    case '/b/demo/schedule': return { room: fixture.readerRoom, schedule: fixture.schedule };
    case '/b/demo/upload': return upload(query, opts);
    case '/pub/demo': return pubState();
    case '/pub/demo/bundle': return { entries: allEntries() };
    case '/pub/demo/roster': return fixture.roster;
    case '/pub/demo/schedule': return fixture.schedule;
    case '/pub/demo/cats': return fixture.catmap;
    case '/pub/demo/qpacket':
      if (!Number.isInteger(round) || round < 1) err('bad round');
      if (!roundDone(round)) err('round in progress');
      return packetFor(round);
    default:
      if (p.startsWith('/pub/demo/qbj/')) {
        const e = allEntries().find((x) => x.id === Number(p.slice('/pub/demo/qbj/'.length)));
        if (!e) err('no such file');
        return e.qbj;
      }
      err('not in the demo');
  }
}

/* ---------- page dressing (browser only) ---------- */

const inDemoPage = typeof location !== 'undefined'
  && ['t', 'b'].some((k) => new URLSearchParams(location.search).get(k) === 'demo');
if (typeof document !== 'undefined' && inDemoPage) {
  // What a real viewer gets by entering the buzzpoints password.
  try { sessionStorage.setItem(BUZZ_KEY, JSON.stringify({ tok: 'demo', v: 'demo' })); }
  catch (e) { /* storage blocked: the tab just asks for any password */ }

  const strip = document.createElement('div');
  strip.className = 'annstrip';
  strip.innerHTML = '<span class="k">demo</span>'
    + '<span class="muted">simulated tournament, stored in this browser</span>'
    + '<span class="spacer" style="flex:1"></span>'
    + '<a href="demo.html">about</a> <a href="#" id="demoreset">reset</a>';
  document.body.prepend(strip);
  strip.querySelector('#demoreset').onclick = (e) => {
    e.preventDefault();
    reset();
    location.href = location.pathname + location.search.replace(/&g=[^&]*/, '');
  };
}
