// demo.js — the demo tournament's backend, entirely in the browser.
//
// api.js routes pub() here whenever the page opened with ?t=demo, ?a=demo,
// or ?b=demo / ?b=demo-b (the slug is reserved server-side; real bucket
// secrets are 20-char random tokens, so the two demo secrets can never
// collide with one), so the REAL pages — index.html (the TD hub), t.html,
// read.html, bucket.html — run unmodified against a committed fixture
// instead of the Worker, the same idea as the archive's useFrozenData.
// Unlike the archive, the demo is live: games a visitor reads in the
// embedded MODAQ upload into localStorage and flow into stats,
// buzzpoints, and categories exactly as at a real tournament, and the
// TD hub's advance-round button works.
//
// The fixture (app/demo/fixture.js, generated by tools/demo_fixture.mjs)
// holds a 4-team triple round robin with rounds 1-6 played plus round 7's
// Room B game; the visitor's room is Room A, whose round-7 game —
// Stanford vs Berkeley, both 5-1, their rubber match — is live. Reading
// and uploading it completes round 7, which also unlocks the round on the
// buzzpoints tab (the same every-room-is-done gate the Worker applies).
//
// Nothing here touches the network (the unit suite runs the whole flow
// with fetch stubbed to throw). Uploads live under one localStorage key;
// reset() clears them plus the reader's per-game stores and the advanced
// round.

import fixture from '../demo/fixture.js';
import { parseMatch, matchPayload } from '../engine/qbj.js';

const UPLOADS_KEY = 'qbtdDemoUploads';
const ROUND_KEY = 'qbtdDemoRound'; // TD-hub advance-round override
const BUZZ_KEY = 'qbtdBuzzKey:demo'; // pubview's sessionStorage slot for slug 'demo'
const FIRST_LOCAL_ID = 1000; // sorts after every fixture id, so re-reads win dedupe

// bucket secret -> room index; each demo room is a working bucket
const SECRETS = { demo: 0, 'demo-b': 1 };

// Browser storage when present, in-memory otherwise (node tests; node's
// experimental localStorage global is method-less without a flag, so
// check capability, not existence).
const mem = new Map();
const usable = typeof localStorage !== 'undefined'
  && typeof localStorage.getItem === 'function'
  && typeof localStorage.removeItem === 'function'
  && typeof localStorage.key === 'function';
const local = usable ? localStorage : {
  getItem: (k) => (mem.has(k) ? mem.get(k) : null),
  setItem: (k, v) => mem.set(k, String(v)),
  removeItem: (k) => mem.delete(k),
  get length() { return mem.size; },
  key: (i) => [...mem.keys()][i],
};

function uploads() {
  try {
    const list = JSON.parse(local.getItem(UPLOADS_KEY));
    return Array.isArray(list) ? list : [];
  } catch (e) { return []; }
}

function saveUploads(list) {
  local.setItem(UPLOADS_KEY, JSON.stringify(list));
}

function currentRound() {
  const n = Number(local.getItem(ROUND_KEY));
  return Number.isInteger(n) && n >= 1 && n <= 999 ? n : fixture.currentRound;
}

/** Clear everything the demo wrote: uploads, the reader's games, the
    advanced round, the buzzpoints unlock. */
export function reset() {
  local.removeItem(UPLOADS_KEY);
  local.removeItem(ROUND_KEY);
  const stale = [];
  for (let i = 0; i < local.length; i++) {
    const k = local.key(i);
    if (k && Object.keys(SECRETS).some((s) =>
      k.startsWith(`qbtdMeta:${s}:`) || k.startsWith(`qbtdGame:${s}:`))) stale.push(k);
  }
  for (const k of stale) local.removeItem(k);
  if (typeof sessionStorage !== 'undefined') sessionStorage.removeItem(BUZZ_KEY);
}

/* ---------- route helpers ---------- */

const err = (message) => { throw new Error(message); };

// Fixture games plus everything uploaded from this browser, in the
// public bundle's entry shape.
function allEntries() {
  return [
    ...fixture.entries,
    ...uploads().filter((u) => u.qbj && !u.error).map((u) => ({
      id: u.id, round: u.round, room: u.room, filename: u.filename, qbj: u.qbj,
    })),
  ];
}

function scheduledGames(round) {
  for (const ph of fixture.schedule.phases) {
    for (const r of ph.rounds) if (r.round === round) return r.games.length;
  }
  return fixture.rooms.length;
}

// The Worker's rule: a round is done when every scheduled game is in.
function roundDone(round) {
  const rooms = new Set(allEntries().filter((e) => e.round === round).map((e) => e.room));
  return rooms.size >= scheduledGames(round);
}

const allPacketRounds = () => Object.keys(fixture.packets).map(Number).sort((x, y) => x - y);
// like the Worker, read surfaces see packets up to the live round only
const packetRounds = () => allPacketRounds().filter((n) => n <= currentRound());

const packetName = (n) => fixture.packets[n].name + '.json';

function packetFor(round) {
  if (round > currentRound()) err('not the live round yet');
  const p = fixture.packets[round];
  if (!p) err('no packet for round ' + round);
  return p;
}

/* ---------- moderator routes (/b/<secret>) ---------- */

function bucketState(room) {
  const roomName = fixture.rooms[room];
  const list = uploads().filter((u) => u.room === roomName);
  return {
    tournament: fixture.name,
    room: roomName,
    current_round: currentRound(),
    closes: Date.now() + 48 * 3600 * 1000,
    packet: packetRounds().includes(currentRound())
      ? { number: currentRound(), packet_name: packetName(currentRound()) } : null,
    packets: packetRounds().map((n) => ({ number: n, packet_name: packetName(n) })),
    roster: true,
    settings: fixture.settings,
    announce: [],
    uploads: [...list].reverse().map(({ qbj, room: _r, ...u }) => u),
    upload_count: list.length,
  };
}

async function upload(room, query, opts) {
  const filename = query.get('name') || 'upload.qbj';
  let round = Number(query.get('round'));
  if (!Number.isInteger(round) || round < 1 || round > 999) round = currentRound();

  let body = opts && opts.body;
  if (body && typeof body !== 'string' && typeof body.text === 'function') body = await body.text();
  if (!body) err('empty file');

  const isMatch = /\.qbj$/i.test(filename) || /\.qbtd\.json$/i.test(filename);
  const kind = /\.qbj$/i.test(filename) ? 'qbj'
    : /\.qbtd\.json$/i.test(filename) ? 'combined'
      : /_game\.json$/i.test(filename) ? 'game' : 'other';
  let error = null;
  let qbj = null;
  if (isMatch) {
    try {
      qbj = matchPayload(JSON.parse(body));
      parseMatch(qbj, { filename });
    } catch (e) {
      error = e.message;
      qbj = null;
    }
  }

  const list = uploads();
  const id = list.reduce((n, u) => Math.max(n, u.id), FIRST_LOCAL_ID - 1) + 1;
  list.push({
    id, round, kind, filename, size: body.length, error,
    created: Date.now(), qbj, room: fixture.rooms[room],
  });
  saveUploads(list);
  return { id, filename, round, kind, error, announce: [] };
}

/* ---------- public routes (/pub/demo) ---------- */

function pubState() {
  const entries = allEntries();
  const last = entries[entries.length - 1];
  return {
    name: fixture.name,
    current_round: currentRound(),
    roster: true,
    announce: [],
    schedule: fixture.schedule.updated,
    // Truthy mode shows the tab; the sessionStorage key seeded below
    // stands in for the password a real tournament's viewers enter.
    buzz: 'demo',
    buzz_kdf: null,
    buzz_v: 'demo',
    buzz_done: packetRounds().filter(roundDone),
    packet_rounds: packetRounds(),
    cats: 1,
    version: (last ? last.id : 0) + ':' + entries.length,
    files: entries.map(({ qbj, ...f }) => f),
  };
}

/* ---------- TD hub routes (/a/demo) ---------- */

const bucketId = (roomName) => fixture.rooms.indexOf(roomName) + 1;

function adminDetail() {
  const created = Date.now() - 6 * 3600 * 1000;
  const fixtureBase = fixture.schedule.updated;
  return {
    tournament: {
      id: 1,
      slug: 'demo',
      name: fixture.name,
      current_round: currentRound(),
      published: 1,
      settings: JSON.stringify(fixture.settings),
      announce: '[]',
      roster_r2_key: 't/1/roster.qbj',
      roster_name: 'roster.qbj',
      created,
      closes: created + 48 * 3600 * 1000,
    },
    buckets: Object.entries(SECRETS).map(([secret, i]) => ({
      id: i + 1, room_name: fixture.rooms[i], secret, created,
    })),
    rounds: allPacketRounds().map((n) => ({
      number: n, packet_name: packetName(n), packet_r2_key: 't/1/packet/' + n + '.json',
    })),
    files: allEntries().map((e) => ({
      id: e.id,
      bucket_id: bucketId(e.room),
      round: e.round,
      kind: e.id >= FIRST_LOCAL_ID ? 'combined' : 'qbj',
      r2_key: 't/1/file/' + e.id,
      filename: e.filename,
      size: JSON.stringify(e.qbj).length,
      error: null,
      created: e.id >= FIRST_LOCAL_ID ? e.id : fixtureBase + e.id * 60000,
    })).sort((x, y) => y.created - x.created),
  };
}

// GET /a/demo/file?key=... — the blob store behind the hub's roster,
// schedule, packet, and game-file reads (stats, .yft, zip, report).
function adminFile(key) {
  if (key === 't/1/roster.qbj') return fixture.roster;
  if (key === 't/1/schedule.json') return fixture.schedule;
  let m = /^t\/1\/packet\/(\d+)\.json$/.exec(key || '');
  if (m) return fixture.packets[Number(m[1])] || err('no such packet');
  m = /^t\/1\/file\/(\d+)$/.exec(key || '');
  if (m) {
    const e = allEntries().find((x) => x.id === Number(m[1]));
    if (!e) err('no such file');
    return e.qbj;
  }
  err('no such file');
}

function adminUpdate(body) {
  if (body && body.current_round !== undefined) {
    const n = Number(body.current_round);
    if (!Number.isInteger(n) || n < 1 || n > 999) err('bad round');
    local.setItem(ROUND_KEY, String(n));
    return { ok: true };
  }
  // published is already on; flipping it off would just break the demo
  if (body && body.published !== undefined) return { ok: true };
  err('not in the demo');
}

function adminDeleteFile(id) {
  if (id < FIRST_LOCAL_ID) err('not in the demo');
  const list = uploads().filter((u) => u.id !== id);
  saveUploads(list);
  return { ok: true };
}

/* ---------- the pub() entry point ---------- */

/** Handle one api.js pub() call. Same success values and thrown
    user-facing errors as the Worker routes it stands in for. */
export async function demoPub(path, opts = {}) {
  const q = path.indexOf('?');
  const p = q < 0 ? path : path.slice(0, q);
  const query = new URLSearchParams(q < 0 ? '' : path.slice(q + 1));
  const round = Number(query.get('round'));
  const method = (opts.method || 'GET').toUpperCase();

  const bucket = /^\/b\/([^/]+)(\/.*)?$/.exec(p);
  if (bucket) {
    const room = SECRETS[bucket[1]];
    if (room === undefined) err('bad link');
    switch (bucket[2] || '') {
      case '': return bucketState(room);
      case '/packet': return packetFor(Number.isInteger(round) && round >= 1 ? round : currentRound());
      case '/roster': return fixture.roster;
      case '/schedule': return { room, schedule: fixture.schedule };
      case '/upload': return upload(room, query, opts);
      default: err('not in the demo'); // tiebreakers etc.
    }
  }

  if (p === '/a/demo' || p.startsWith('/a/demo/')) {
    const rest = p.slice('/a/demo'.length);
    if (rest === '' && method === 'GET') return adminDetail();
    if (rest === '' && method === 'POST') {
      let body = null;
      try { body = opts.json !== undefined ? opts.json : JSON.parse(opts.body); }
      catch (e) { /* fall through to the reject below */ }
      return adminUpdate(body);
    }
    if (rest === '/file') return adminFile(query.get('key'));
    if (rest === '/bundle' && method === 'POST') {           // always materialized here
      let body = null;
      try { body = JSON.parse(opts.body); } catch (e) { /* count nothing */ }
      return { entries: (body && body.entries || []).length };
    }
    const del = /^\/files\/(\d+)$/.exec(rest);
    if (del && method === 'DELETE') return adminDeleteFile(Number(del[1]));
    err('not in the demo'); // rooms/packets/roster/schedule edits, rotate
  }

  switch (p) {
    case '/pub/demo': return pubState();
    case '/pub/demo/bundle': return { entries: allEntries() };
    case '/pub/demo/roster': return fixture.roster;
    case '/pub/demo/schedule': return fixture.schedule;
    case '/pub/demo/cats': return fixture.catmap;
    case '/pub/demo/qpacket':
      if (!Number.isInteger(round) || round < 1) err('bad round');
      if (!roundDone(round)) err('round in progress');
      return packetFor(round);
    default:
      if (p.startsWith('/pub/demo/qbj/')) {
        const e = allEntries().find((x) => x.id === Number(p.slice('/pub/demo/qbj/'.length)));
        if (!e) err('no such file');
        return e.qbj;
      }
      err('not in the demo');
  }
}

/* ---------- page dressing (browser only) ---------- */

const inDemoPage = typeof location !== 'undefined'
  && (['t', 'a'].some((k) => new URLSearchParams(location.search).get(k) === 'demo')
    || SECRETS[new URLSearchParams(location.search).get('b')] !== undefined);
if (typeof document !== 'undefined' && inDemoPage) {
  // What a real viewer gets by entering the buzzpoints password.
  try { sessionStorage.setItem(BUZZ_KEY, JSON.stringify({ tok: 'demo', v: 'demo' })); }
  catch (e) { /* storage blocked: the tab just asks for any password */ }

  const strip = document.createElement('div');
  strip.className = 'annstrip';
  strip.innerHTML = '<span class="k">demo</span>'
    + '<span class="muted">simulated tournament, stored in this browser</span>'
    + '<span class="spacer" style="flex:1"></span>'
    + '<a href="demo.html">about</a> <a href="#" id="demoreset">reset</a>';
  document.body.prepend(strip);
  strip.querySelector('#demoreset').onclick = (e) => {
    e.preventDefault();
    reset();
    location.href = location.pathname + location.search.replace(/&g=[^&]*/, '');
  };
}
