-- Migration for the directory (worker.js "the directory": the home page's
-- list of tournaments running on this instance). Apply BEFORE deploying a
-- Worker that names the column — the tick reads and writes dir_entry:
--   npx wrangler d1 execute qb-td --remote --file migrate-directory.sql
-- then run schema.sql again for the two new indexes (it is re-runnable):
--   npx wrangler d1 execute qb-td --remote --file schema.sql
-- Not re-runnable: the ALTER fails once the column exists.
--
-- dir_entry — the tournament's line in the directory as JSON, NULL while
--             it isn't listed. Nothing to backfill: the list is of what
--             is running, and a running tournament gets its entry from
--             the tick the next time a room uploads.
ALTER TABLE tournaments ADD COLUMN dir_entry TEXT;
